version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: groupbuy_postgres
    environment:
      POSTGRES_DB: groupbuy_db
      POSTGRES_USER: groupbuy
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - groupbuy_network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: groupbuy_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - groupbuy_network

  # Group Buying API (GBGCN)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groupbuy_api
    environment:
      - DATABASE_URL=postgresql://groupbuy:password@postgres:5432/groupbuy_db
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - ENVIRONMENT=development
      - SECRET_KEY=your-super-secret-key-for-development
      # GBGCN Model Parameters
      - EMBEDDING_DIM=64
      - NUM_GCN_LAYERS=3
      - DROPOUT_RATE=0.1
      - LEARNING_RATE=0.001
      - ALPHA=0.6
      - BETA=0.4
      - BATCH_SIZE=512
      - MAX_EPOCHS=500
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - groupbuy_network
    restart: unless-stopped

  # Celery Worker for background tasks
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groupbuy_celery
    command: celery -A src.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://groupbuy:password@postgres:5432/groupbuy_db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    networks:
      - groupbuy_network
    restart: unless-stopped

  # Celery Beat for scheduled tasks
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groupbuy_celery_beat
    command: celery -A src.tasks.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://groupbuy:password@postgres:5432/groupbuy_db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    networks:
      - groupbuy_network
    restart: unless-stopped

  # Jupyter Notebook for GBGCN experimentation
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: groupbuy_jupyter
    environment:
      - DATABASE_URL=postgresql://groupbuy:password@postgres:5432/groupbuy_db
      - REDIS_URL=redis://redis:6379
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./notebooks:/app/notebooks
      - ./models:/app/models
      - ./data:/app/data
      - ./src:/app/src
    networks:
      - groupbuy_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  groupbuy_network:
    driver: bridge 